name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *' # Daily at 2 AM UTC

env:
  NODE_VERSION: '20.x'

jobs:
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check if E2E tests exist
        id: check_tests
        run: |
          if [ -f "playwright.config.ts" ] && [ -d "tests/e2e" ]; then
            echo "tests_exist=true" >> $GITHUB_OUTPUT
          else
            echo "tests_exist=false" >> $GITHUB_OUTPUT
            echo "⚠️ No E2E tests found, skipping Playwright tests"
          fi

      - name: Install Playwright browsers
        if: steps.check_tests.outputs.tests_exist == 'true'
        run: npx playwright install --with-deps

      - name: Build application
        run: npm run build

      - name: Run Playwright tests
        if: steps.check_tests.outputs.tests_exist == 'true'
        run: npx playwright test
        env:
          # Use preview server for testing
          PLAYWRIGHT_BASE_URL: http://localhost:4173

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always() && steps.check_tests.outputs.tests_exist == 'true'
        with:
          name: playwright-report-${{ github.sha }}
          path: playwright-report
          retention-days: 7

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always() && steps.check_tests.outputs.tests_exist == 'true'
        with:
          name: test-results-${{ github.sha }}
          path: test-results
          retention-days: 7